spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:postgresql://localhost:5432/abscence_db
    username: postgres
    password: nixon

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/